language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.10'
before_script:
  - npm install -g yarn
  - yarn cache clean
  - yarn install
script:
  - yarn test:prod
after_success:
  - ./scripts/upload-coverage.sh
  - ./scripts/gh-pages-publish.js

